var myString;
var myNum;
var myBool;
var myVar;
// let strArr: string[];
var numArr;
var boolArr;
var strArr;
var strNumTuple;
myString = "Hello world";
myNum = 22;
myBool = true;
myVar = 5;
strArr = ['Hello', 'World'];
numArr = [123, 321];
boolArr = [true, false, true];
strNumTuple = ['Hello', 4];
var myVoid = undefined;
var myNull = null;
var myUndefined = null;
// console.log(myString);
// console.log(myNum);
// console.log(myBool);
// console.log(myVar);
// console.log(strArr);
// console.log(numArr);
// console.log(boolArr);
// console.log(strNumTuple);
console.log(myVoid);
